# Generated by Django 6.1 on 2026-08-11 15:06

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('currency', models.CharField(help_text='The asset this account holds, e.g. BTC, ETH or USD. Typed in free-form.', max_length=20)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, help_text='Positive debits the account, negative credits it.', max_digits=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='main.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='main.transaction')),
            ],
            options={
                'verbose_name_plural': 'entries',
                'ordering': ['transaction__occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=18, help_text='Always positive: the quantity consumed on both sides.', max_digits=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_credit', to='main.entry')),
                ('debit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_debit', to='main.entry')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'ordering': ['debit__transaction__occurred_at', 'id'],
                'constraints': [models.UniqueConstraint(fields=('debit', 'credit'), name='match_unique_pair'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='match_quantity_positive')],
            },
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('quantity', 0), _negated=True), name='entry_quantity_nonzero'),
        ),
    ]
