# Generated by Django 6.1 on 2026-08-11 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('zar_per_btc', models.DecimalField(decimal_places=18, help_text='The price of one BTC in ZAR on this date.', max_digits=32)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('ZAR', 'ZAR — South African rand'), ('BTC', 'BTC — Bitcoin')], default='ZAR', help_text='The asset this account holds.', max_length=3),
        ),
    ]
