# Generated by Django 6.1 on 2026-08-11 15:35, then rewritten to keep the existing dates:
# the generated version dropped occurred_at and added occurred_on, losing every date already
# recorded. Renaming and narrowing the column keeps them; the UPDATE drops the time of day
# that the old datetime values still carry.

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_exchangerate_alter_account_currency'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='occurred_at',
            new_name='occurred_on',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='occurred_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.RunSQL(
            'UPDATE main_transaction SET occurred_on = substr(occurred_on, 1, 10)',
            migrations.RunSQL.noop,
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['transaction__occurred_on', 'id'], 'verbose_name_plural': 'entries'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['debit__transaction__occurred_on', 'id'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-occurred_on', '-id']},
        ),
    ]
