# Generated by Django 6.1 on 2026-08-12 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rate_per_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='match_fifo',
            field=models.BooleanField(default=True, help_text='Whether the credit on this transaction is matched against earlier debits.'),
        ),
    ]
